services:
  - type: web
    name: shadownet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: COOKIE_SECURE
        value: "1"
